[api]
AZURE_OPENAI_ENDPOINT = "https://dx-internal.openai.azure.com/"
AZURE_OPENAI_API_KEY = "7g2v7do6VyF92G6GbCpN9NMSv5DSMW8ubCFjufudt1T08kcr4pTvJQQJ99BEACYeBjFXJ3w3AAABACOGItiC"
AZURE_OPENAI_DEPLOYMENT = "gpt-4o"
AZURE_OPENAI_API_VERSION = "2024-12-01-preview"
